### ISSUE TITLE
Actividad 1. Unidadad 3 (Hugo Iván Pérez Silva)

### ISSUE THREAD

**Issue by Ivan-PerezZ** [SistemasTecTlaxiaco/actividad-7-proposiciones-l-gicas-Ivan-PerezZ#1]
[Practica 1 MateDisc.pdf](https://github.com/user-attachments/files/17483810/Practica.1.MateDisc.pdf)

**Comment by Juan27231** [comment]
Portada 5/5
Procedimientos 5/5
lista de figuras 3.5/5
Resultados y conclusiones 4.5/5
Calificación 18/20

**Comment by josealfredo79** [comment]
bien hecho y revisado...
